- hosts: dev
  gather_facts: no
  roles:
    - { role: ubuntu, tags: ubuntu, when: target == 'ubuntu'}
    # - { role: centos, tags: centos, when: target == 'centos'}
    - { role: dotfiles, tags: dotfiles }
